# Generated by Django 3.2.7 on 2021-09-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210922_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Estatura'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
    ]
