# Generated by Django 3.2.7 on 2021-09-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Person',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Store',
        ),
        migrations.RemoveField(
            model_name='client',
            name='member',
        ),
        migrations.RemoveField(
            model_name='client',
            name='type',
        ),
        migrations.AddField(
            model_name='client',
            name='Age',
            field=models.IntegerField(default=18, verbose_name='Edad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='CP',
            field=models.IntegerField(default=73800, verbose_name='Codigo Postal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='Lastname1',
            field=models.CharField(default='Apellido', max_length=50, verbose_name='Apellido Paterno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='Lastname2',
            field=models.CharField(default='Apellido2', max_length=50, verbose_name='Apellido Materno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='Location',
            field=models.CharField(default='Location', max_length=50, verbose_name='Localidda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='Municipality',
            field=models.CharField(default='Municipio', max_length=50, verbose_name='Municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='Phone',
            field=models.CharField(default='1234567890', max_length=15, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='State',
            field=models.CharField(default='State', max_length=50, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='Street',
            field=models.CharField(default='Strret', max_length=50, verbose_name='Calle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='firstname',
            field=models.CharField(default='firstname', max_length=50, verbose_name='Nombre(s)'),
            preserve_default=False,
        ),
    ]
