# Generated by Django 3.2.7 on 2021-09-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210924_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Location',
            field=models.CharField(max_length=50, verbose_name='Localidad'),
        ),
    ]
