# Generated by Django 3.2.7 on 2021-09-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_client_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('Lastname1', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('Lastname2', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('Age', models.IntegerField(verbose_name='Edad')),
                ('CP', models.IntegerField(verbose_name='Codigo Postal')),
                ('Location', models.CharField(max_length=50, verbose_name='Localidad')),
                ('Street', models.CharField(max_length=50, verbose_name='Calle')),
                ('Municipality', models.CharField(max_length=50, verbose_name='Municipio')),
                ('State', models.CharField(max_length=50, verbose_name='Estado')),
                ('Phone', models.CharField(max_length=15, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
