# Generated by Django 3.2.7 on 2021-09-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('Lastname1', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('Lastname2', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('Phone', models.CharField(max_length=15, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Proveedorr',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
