# Generated by Django 3.2.7 on 2021-09-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210924_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('Race', models.CharField(max_length=50, verbose_name='Raza')),
                ('Color', models.CharField(max_length=50, verbose_name='Color')),
                ('Age', models.CharField(max_length=50, verbose_name='Edad')),
                ('Specie', models.CharField(max_length=50, verbose_name='Especie')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
    ]
