# Generated by Django 3.2.7 on 2021-09-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_mascot_specie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascot',
            old_name='Specie',
            new_name='type',
        ),
    ]
