# Generated by Django 3.2.7 on 2021-09-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_specie_mascot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascot',
            name='type',
            field=models.CharField(choices=[('Felino', 'Felino'), ('Canino', 'Canino'), ('Reptil', 'Reptil'), ('Ave', 'Ave'), ('Animal de granja', 'Animal de granja'), ('Roedor', 'Roedor')], max_length=20, verbose_name='Especie'),
        ),
    ]
