# Generated by Django 3.2.7 on 2021-09-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_mascot_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascot',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mascot',
            old_name='Race',
            new_name='race',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Name',
            new_name='name',
        ),
    ]
