# Generated by Django 3.2.7 on 2021-09-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
