# Generated by Django 3.2.7 on 2021-09-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('CP', models.IntegerField(verbose_name='Codigo Postal')),
                ('Location', models.CharField(max_length=50, verbose_name='Localidad')),
                ('Street', models.CharField(max_length=50, verbose_name='Calle')),
                ('Municipality', models.CharField(max_length=50, verbose_name='Municipio')),
                ('State', models.CharField(max_length=50, verbose_name='Estado')),
                ('Phone', models.CharField(max_length=15, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
    ]
