# Generated by Django 3.2.7 on 2021-09-24 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sucursal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sucursal',
            new_name='Office',
        ),
    ]
