# Generated by Django 3.2.7 on 2021-09-24 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210924_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cite',
            old_name='Date',
            new_name='date',
        ),
    ]
