# Generated by Django 3.2.7 on 2021-10-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascot',
            name='foto',
            field=models.ImageField(null=True, upload_to='imgMascot', verbose_name='Agregar imagen'),
        ),
    ]
