# Generated by Django 3.2.7 on 2021-11-04 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_mascot_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='firstname',
            new_name='Firstname',
        ),
    ]
