# Generated by Django 3.2.7 on 2021-11-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20211104_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Professional',
            field=models.CharField(default=12345, max_length=15, verbose_name='Cedula Profesional'),
            preserve_default=False,
        ),
    ]
