# Generated by Django 3.2.7 on 2021-11-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_doctor_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Description',
            field=models.CharField(default='adadad', max_length=500, verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
