# Generated by Django 3.2.7 on 2021-11-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_service_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='Name',
        ),
    ]
